eventday/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events
  root 'events#index'
end

eventday/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

eventday/app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

eventday/app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

eventday/app/models/user.rb
class User < ApplicationRecord
  has_many :events
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

eventday/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

eventday/app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :find_event, only: [:show, :edit, :update, :destroy]

  def index
    @event = Event.all.order("created_at DESC")
  end

  def show
  end

  def new
    @event = current_user.events.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end
  def create
    @event = current_user.events.build(event_params)
    @event.category_id = params[:category_id]

    if @event.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def update
    @event.category_id = params[:category_id]
    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    redirect_to root_path
  end


  private

  def event_params
    params.require(:event).permit(:title, :lokasi, :jenis, :deskripsi, :category_id)
  end

  def find_event
    @event = Event.find(params[:id])
end
end

eventday/app/helpers/application_helper.rb
module ApplicationHelper
end

eventday/app/helpers/events_helper.rb
module EventsHelper
end

eventday/app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
<%= f.input :title, label: "Event Title" %>
<%= f.input :lokasi %>
<%= f.input :jenis %>
<%= f.input :deskripsi %>
<%= f.button :submit %>
<% end %>

eventday/app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render 'form' %>

eventday/app/views/events/index.html.erb
<% @event.each do |event| %>
  <h2><%= link_to event.title, event_path(event) %></h2>
  <% end %>

eventday/app/views/events/new.html.erb
<h1>New Event</h1>
<%= render 'form' %>

eventday/app/views/events/show.html.erb
<h2><%= @event.title %></h2>
<h3><%= @event.lokasi %></h3>
<h3>Category: <%= @event.category.name %></h3>
<h3><%= @event.jenis %></h3>
<p><%= @event.deskripsi %></p>
<%= link_to "Back", root_path %>

<% if user_signed_in? %>

<% if @event.user_id == current_user.id %>

<%= link_to "Edit", edit_event_path(@event) %>
<%= link_to "Delete", event_path(@event), method: :delete, data: { confirm: "apa kamu akan menghapus ini?"} %>
<% end %>
<% end %>

eventday/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventday</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default">

      <div class="container">

        <div class="navbar-header">
          <%= link_to "Event Review", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to "Add Event", new_event_path %></li>
          <% end %>

        </ul>

      </div>

    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

  </body>
</html>